README.md, lib/type.js, test/type.js
* Changed the **getType()** Method to be more generic and support ECMA6 as well as custom types
* Deleted NativeTypes as no longer needed
* Added (fake) Tests for ECMA6 types (by stubbing Object.prototype.toString)
* Updated Readme.md with ECMA6 Types 
I'm not sure if the way of treating a change to Object[Symbol.toStringTag] by returnig the given value is the right one - maybe it should actually return just 'object'. On the other hand: Whoever uses this probably knows what he is doing and won't have a problem with it.
=> Included support for ECMA6 types

README.md, lib/type.js, test/type.js
With all the dazzle about the promises, i totally forgot about the other Spec we were talking with `new String()` returning type `string` instead of `object`. I changed that now and also added a test to make sure `new Number()` actually returns type `number`.
Sorry for this :D
=> "new String()" as 'string' instead of 'object'

.travis.yml
I forgot this option is needed for saucelabs to work in travis.
=> chore(build): add sauce_connect addon option to travis

README.md
The gitter link pointed to a non existing channel *type-detect*. I pointed it to the chai-js channel.
=> docs: Fixed gitter chat URL to point to chaijs-channel

test/index.js
Symbol.toStringTag is an available read only property in Node 6. The tests overwrite the property
and as such were failing in Node 6.0. This fixes the tests so that they don't assign on Symbol
if the property already exists.
It also alters the tests to use Symbol.toStringTag proper, rather than the sham string - so that
when toStringTag actually exists, it is actually used rather than the sham; allowing tests to pass
in environments which support toStringTag for real.
@lucasfcosta @davelosert if you could please check this over and merge when happy 😄
=> test: Fix tests running in Node 6.0

index.js, test/index.js
Some browser versions support `Symbol` but don't support `Symbol.toStringTag`, causing type-detect to always return `undefined`.
This PR fixes the bug and thus resolves the error identified by @davelosert in https://github.com/chaijs/chai/pull/640.
=> fix: check if Symbol.toStringTag exists before using

README.md
As you can currently see on the README we've got a minor problem with the Node link.
=> fix: fixed link for node formatting on README.md

bench/index.js, index.js
Im the midst of trying to speed up deep-eql I noticed that type detecting on typed arrays seemed to hit the slow path (`Object.prototype.toString.call`). That's when I noticed that we don't hit a path at all where if `toStringTag` is a string, we can just return early with it.
So this PR gives us a shortcut to getting to the final result, with what looks to be about a ~5-6x increase in ops/sec.
=> Speed up tostringtag objects

README.md, index.js, test/dom.js, test/index.js, test/new-ecmascript-types.js
We're sacrificing a lot of performance just to lowercase the string values, which is not ideal as it's not always necessary. Here are some numbers demonstrating the difference in performance:
With `.toLowerCase()`:
```
string literal     x 31,742,089 ops/sec ±6.85% (70 runs sampled)
array literal      x 12,508,545 ops/sec ±3.86% (67 runs sampled)
boolean literal    x 33,502,011 ops/sec ±3.58% (66 runs sampled)
object literal     x 1,178,855 ops/sec ±2.06% (79 runs sampled)
object from null   x 3,356,249 ops/sec ±2.03% (81 runs sampled)
regex literal      x 2,738,477 ops/sec ±1.95% (80 runs sampled)
number literal     x 30,119,855 ops/sec ±2.04% (78 runs sampled)
promise            x 7,260,140 ops/sec ±1.79% (81 runs sampled)
null               x 34,793,675 ops/sec ±1.58% (84 runs sampled) …
```
=> perf: do not lowercase returned values

index.js
Currently it is checking for it on the Array prototype, which is incorrect as a browser could have the Array iterators and not have the String iterators.
=> Make sure stringIteratorExists is checking for iterator function on String prototype

bench/index.js, index.js, karma.conf.js, package.json, test/dom.js, test/index.js, test/new-ecmascript-types.js, test/node.js
This commit updates all dependencies. After this we should be able to get gk running properly - as I'm not sure it is right now.
=> chore: update package dependencies

index.js, test/index.js, test/tostringtag-extras.js
Closes #49. Supersedes #50 by adding tests. Thanks @dvlsg!
=> fix: favour extended array toStringTag where available

index.js
Due to the fact that I made the huge mistake of merging #95 before seeing @shvaikalesh's comment about triggering the `Symbol.toStringTag` getter in `obj` I think it was better to just fix this in a separate PR than reverting stuff and putting it back in.
I'm really sorry for this 😓
=> Do not call getter when checking for Symbol.toStringTag in obj

index.js
Instead uses `globalObject.HTMLElement`, to avoid breaking in a node environment where `HTMLElement` is not defined.
Closes #98
=> Don't assume HTMLElement is in the global scope

.travis.yml, karma.conf.js
=> fix(karma): ensure job number reflects CI environment

.travis.yml
This regenerates our GH_TOKEN and NPM_TOKEN, which should get the build releasing properly. 
Fixes #113
=> chore(travis): regenerate GH_TOKEN, NPM_TOKEN

.travis.yml
BUILD_LEADER_ID is needed for semantic-release to pick the right job that
semantic-release publishes under. The default behavior for semantic-release
is to elect a build using the latest node version (which in our case is job
9). This var fixes the job to job 10, which is the actual job we have to
run semantic-release.
This should _actually_ _really_ _properly_ fix the build now 😅
=> chore(travis): ensure BUILD_LEADER_ID is fixed to job number

package.json
This changes the `contributors` field in the package.json for type-detect to reflect the list available at https://github.com/chaijs/type-detect/graphs/contributors. There are two notable omissions from the list: Greenkeeper Bot (which is a bot) and `locigalparadox` - who is listed in the `author` field.
=> chore(package): list all contributors

index.js
Caching the existence of `window` introduces problems in quasi-browser
environments where it's not uncommon to unset `window` before some tests.
Fixes #133
=> fix: stop caching existence of `window`

index.js
The current check for `window` doesn't cover the scenario were `window` is `null`:
https://github.com/chaijs/type-detect/blob/master/index.js#L104
Setting window to `null` bypasses the current `window` check and errors when trying to read `location` off of it.
While I would encourage users to set the `window` to `undefined` when they're resetting in tests, not everyone will.  This is a small PR to fix that.
=> Better check for the existence of window

.travis.yml
As far as I can tell `xvfb` is not needed when running tests in headless browsers.
From [Getting Started with Headless Chrome](https://developers.google.com/web/updates/2017/04/headless-chrome):
>So I still need Xvfb?
>
>No. Headless Chrome doesn't use a window so a display server like Xvfb is no longer needed. You can happily run your automated tests without it.
>
>What is Xvfb? Xvfb is an in-memory display server for Unix-like systems that enables you to run graphical applications (like Chrome) without an attached physical display. Many people use Xvfb to run earlier versions of Chrome to do "headless" testing.
=> remove xvfb pre-test step in travis

README.md
When importing type-detect in the browser, the function is called 'typeDetect'
If the usage examples are followed as-is, the browser will throw an error indicating that type() is not defined.
In order to run the examples as written in the browser, the user should declare a variable type that refers to typeDetect(). An alternative would be to provide another set of browser-specific examples using typeDetect() instead of type(), but I think that would be overly verbose and confusing.
=> Clarify browser usage. #139

.gitignore, README.md, index.ts, package-lock.json, package.json, test/deno-test.ts, tsconfig.json
This PR updates the codebase to use TypeScript, and also adds "support" for [Deno](https://deno.land/). Support for Deno consists of adding a note to the readme, and adding a test file to make sure everything works correctly.
=> Switch to TypeScript, add support for Deno
